name: CI/CD with GHCR

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

  docker-build-push:
    runs-on: ubuntu-latest
    needs: ci-checks
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          IMAGE_ID=ghcr.io/danish-mar/astr
          VERSION=${{ github.sha }}
          echo "Building $IMAGE_ID:$VERSION"
          docker build -t $IMAGE_ID:$VERSION -t $IMAGE_ID:latest .

      - name: Push Docker image
        run: |
          IMAGE_ID=ghcr.io/danish-mar/astr
          VERSION=${{ github.sha }}
          docker push $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:latest
